# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d94381c5973326a6cf0f091c12d5f449c89db17a47973bff33ae41d1ca783e528ec953bf5da3dd905176b5e246d01b789e12518268b023e986206082a52ac3f5

test:
  secret_key_base: 2d7a0f9e80720e5ca9a4285a3121a1593f8372974917c501c2230c33fd2b393c1dcd7e49d337403556791c0bb021313fd8256deb6c7a774620680c1e696e4eda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
